# End-to-end
SBIDS: [10809, 10812]
WORKDIR: "/mnt/shared/home/ashen/tmp"

# Download
CREDENTIALS: 'credentials.ini'

# Linmos
LINMOS_OUTPUT_IMAGE: "mosaicked"
LINMOS_CONFIG: "linmos.config"
LINMOS_CLUSTER_OPTIONS: "--ntasks=324 --ntasks-per-node=18"

# SoFiA-2

# SoFiAX
